kind: Deployment
apiVersion: apps/v1
metadata:
  name: live-puppet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-puppet
  template:
    metadata:
      labels:
        app: live-puppet
    spec:
      containers:
      - image: camillecxy/live-puppet:tcp32504
        imagePullPolicy: IfNotPresent
        name: live-puppet
        resources: {}
        ports:
        - containerPort: 32504
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred